name: CI

on:
  push

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ubuntu-latest
      
    steps:
    # - name: Install gtest 
    #   run:  |
    #     cd /tmp/
    #     git clone https://github.com/google/googletest.git -b release-1.10.0
    #     cd googletest        # Main directory of the cloned repository.
    #     mkdir build          # Create a directory to hold the build output.
    #     cd build
    #     cmake ..             # Generate native build scripts for GoogleTest.
    #     make
    #     sudo make install    # Install in /usr/local/ by default

    # - name: Install yaml-cpp 
    #   run:  |
    #     sudo apt install libyaml-cpp-dev
          
    # - name: Checkout
    #   uses: actions/checkout@v2

    # - name: Cache Qt
    #   id: cache-qt
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ runner.workspace }}/Qt
    #     key: ${{ runner.os }}-QtCache

    # - name: Install Qt
    #   uses: jurplel/install-qt-action@v2
    #   with:
    #     cached: ${{ steps.cache-qt.outputs.cache-hit }}

    # - name: Build All
    #   run: |
    #     cmake -E make_directory ${{ github.workspace }}/build
    #     cd ${{ github.workspace }}/build
    #     cmake  ..
    #     make

    # - name: Run Unit Tests
    #   run: |       
    #     cd ${{ github.workspace }}/build/tests/
    #     sudo ./tests

    - name: Increase Version
      run: |
        pwd
        ls
        cd bin
        touch foo.txt
        # sed -i 's/0.1.1/0..1.2/g' file.txt