name: Test Coverage

on:
  pull_request:
    types: 
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Coverage
        run: python ${{ GITHUB.WORKSPACE }}/SpaceLoader/tests/ceoverage.py
      
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            # readme yi parçalayan kod yazılacak ve coveerage değiştirilecek
          
      - name: push-new-version
        run: |
          cd ${{ GITHUB.WORKSPACE }}/SpaceLoader/
          git add ./version.h
          git commit -m "Updated Version File. New Version is $VERSION"
          git push