name: Update Version

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            env_file = os.getenv('GITHUB_ENV')
            versionFile = open('${{ GITHUB.WORKSPACE }}/SpaceLoader/version.h', 'r')
            lines = versionFile.readlines()
            fullVersion = lines[3].split(" = ")[1].replace('"', '').replace(';', '')
            updatedFullVersion = fullVersion.split('.')[0] + '.' + str(int(fullVersion.split('.')[1]) + 1)
            lines[3] = lines[3].split(" = ")[0] + ' = "' + updatedFullVersion + '";\n'
            versionFile = open('${{ GITHUB.WORKSPACE }}/SpaceLoader/version.h', 'w')
            versionFile.writelines(lines)
            with open(env_file, "a") as myfile:
                myfile.write("VERSION={}".format(updatedFullVersion))
          
      - name: push-new-version
        run: |
          cd ${{ GITHUB.WORKSPACE }}/SpaceLoader/
          git add ./version.h
          git commit -m "Updated Version File. New Version is $VERSION"
          git push
