name: Actions Workflow 

on:
  push:

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: patchVersioning
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          cd SpaceLoader/bin
          fullVersion=$(cat VERSION)
          minorVersion=${fullVersion#*.}
          majorVersion=$(cut -d'.' -f1 <<<"$fullVersion")
          updatedMinorVersion=$((minorVersion+1))
          majorVersion+=minorVersion
          versionMessage="Updated Version File. New Version is "
          updatedVersion+=$versionMessage
          updatedVersion+=majorVersion
          echo $majorVersion | tee VERSION
          git add VERSION
          git commit -m $updatedVersion
          git push