name: Actions Workflow 

on:
  push:
    branches:
      -main

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: patchVersioning
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          cd SpaceLoader/bin
          fullVersion=$(cat VERSION)
          minorVersion=${fullVersion#*.}
          majorVersion=$(echo $fullVersion | cut -d'.' -f1)
          updatedMinorVersion=$((minorVersion+1))
          dot="."
          updatedFullVersion=$majorVersion$dot$updatedMinorVersion
          versionMessage="Updated Version File. New Version is $updatedFullVersion"
          echo $updatedFullVersion | tee VERSION
          git add ./VERSION
          git commit -m "$versionMessage"
          git push