name: Actions Workflow 

on:
  push:

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: patchVersioning
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          cd SpaceLoader/bin
          fullversion=$(cat VERSION)
          minorversion=${fullversion#*.}
          majorversion=$(cut -d'.' -f1 <<<"$fullVersion")
          updatedminorversion=$((minorversion+1))
          majorversion+=$updatedminorversion
          versionmessage="Updated Version File. New Version is "
          updatedversion+=$versionmessage
          updatedversion+=$majorversion
          echo $majorversion | tee VERSION
          git add .
          git commit -m $updatedversion
          git push