name: Actions Workflow 

on:
  push:
    branches:
      -main
      
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: patchVersioning
        run: | 
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rendayigit/SpaceLoader.git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          cd SpaceLoader/bin
          fullversion=$(cat VERSION)
          minorversion=${fullversion#*.}
          majorversion=$(echo $fullversion | cut -d'.' -f1)
          updatedminorversion=$((minorversion+1))
          dot="."
          majorversion+=$dot
          majorversion+=$updatedminorversion
          versionmessage="Updated Version File. New Version is $majorversion"
          echo $majorversion | tee VERSION
          git add .
          git commit -m "$versionmessage"
          git push