name: WINDOWS_CI

on: push

defaults:
  run:
    shell: cmd

jobs:
  CI:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/msys2/
          key: msys2-cache

      - name: Install MSYS2 and Build All
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir ${{github.workspace}}/msys2/
          cd ${{github.workspace}}/msys2/
          curl -LO http://github.com/msys2/msys2-installer/releases/download/2022-12-16/msys2-x86_64-20221216.exe --ssl-no-revoke
          msys2-x86_64-20221216.exe install --root ${{github.workspace}}/msys2/ --confirm-command

          cd ${{github.workspace}}/msys2/usr/bin/
          pacman.exe -S mingw-w64-x86_64-gcc --noconfirm
          pacman.exe -S mingw-w64-x86_64-qt5 --noconfirm
          pacman.exe -S mingw-w64-x86_64-qt5-base --noconfirm
          pacman.exe -S mingw-w64-x86_64-qt5-declarative --noconfirm
          pacman.exe -S mingw-w64-x86_64-cmake --noconfirm
          pacman.exe -S mingw-w64-x86_64-make --noconfirm
          pacman.exe -S mingw-w64-x86_64-gtest --noconfirm
          pacman.exe -S mingw-w64-x86_64-yaml-cpp --noconfirm
          pacman.exe -S mingw-w64-x86_64-ninja --noconfirm

          rm -rf c:/programdata/chocolatey/

          set PATH=%PATH%;${{github.workspace}}/msys2/usr/bin/
          set PATH=%PATH%;${{github.workspace}}/msys2/mingw64/bin/

          mkdir ${{github.workspace}}/build
          ${{github.workspace}}/msys2/mingw64/bin/cmake.exe -DCMAKE_PREFIX_PATH:STRING=${{github.workspace}}/msys2/mingw64/lib/cmake/ -DCMAKE_BUILD_TYPE:STRING=Release -S ${{github.workspace}} -B ${{github.workspace}}/build/ -G "MinGW Makefiles"
          ${{github.workspace}}/msys2/mingw64/bin/cmake.exe --build ${{github.workspace}}/build/ --config Release --target all
        env:
          CC: ${{github.workspace}}/mingw64/bin/gcc.exe
          CXX: ${{github.workspace}}/mingw64/bin/g++.exe