# name: WINDOWS_CI_2

# on: push

# jobs:
#   build:
#     runs-on: windows-latest
#     defaults:
#       run:
#         shell: msys2 {0}
        
#     steps:
#       - name: Install MSYS2
#       - uses: msys2/setup-msys2@v2
#         with:
#           msystem: MINGW64
#           update: true
#           install: |
#             mingw-w64-x86_64-qt5
#             mingw-w64-x86_64-qt5-base
#             mingw-w64-x86_64-qt5-declarative
#             mingw-w64-x86_64-cmake
#             mingw-w64-x86_64-make
#             mingw-w64-x86_64-gtest
#             mingw-w64-x86_64-yaml-cpp

#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Build All
#         run: |
#           # TODO - find the correct path to the msys installation
#           mkdir rendayigit/SpaceLoader/build
#           cmake -DCMAKE_PREFIX_PATH:STRING=D:/a/_temp/msys64/mingw64/lib/cmake/ -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CC_COMPILER:FILEPATH=D:/a/_temp/msys64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:/a/_temp/msys64/mingw64/bin/g++.exe -S D:/a/SpaceLoader/SpaceLoader/ -B D:/a/SpaceLoader/SpaceLoader/build/ -G "MinGW Makefiles"
#           set /a coreCount=%NUMBER_OF_PROCESSORS% + 2
#           cmake --build rendayigit/SpaceLoader/build/ --config Debug --target all -j %coreCount% --

#       - name: Run Unit Tests
#         run: |
#           cd D:\a\SpaceLoader\SpaceLoader\build\tests\
#           ./tests.exe


name: WINDOWS_CI_2

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
        run:
          shell: cmd
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-declarative
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-yaml-cpp
            mingw-w64-x86_64-ninja     

      - name: Checkout
        uses: actions/checkout@v2

      - shell: cmd
        run: echo %PATH%

      - name: Build All
        run: |
            # TODO - find the correct path to the msys installation
            mkdir D:/a/SpaceLoader/SpaceLoader/build/
            cmake -DCMAKE_PREFIX_PATH:STRING=D:/msys64/mingw64/lib/cmake/ -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CC_COMPILER:FILEPATH=D:/msys64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:/msys64/mingw64/bin/g++.exe -S D:/a/SpaceLoader/SpaceLoader/ -B D:/a/SpaceLoader/SpaceLoader/build/ -G "MinGW Makefiles"
            set /a coreCount=%NUMBER_OF_PROCESSORS% + 2
            cmake --build D:/a/SpaceLoader/SpaceLoader/build --config Debug --target all -j %coreCount% --

      - name: Run Unit Tests
        run: |
            cd D:/a/SpaceLoader/SpaceLoader/build/tests/
            ./tests.exe