name: WINDOWS_CI

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-declarative
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-yaml-cpp
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          host: "windows"
          target: "desktop"

      - name: Build All
        run: |
          # cd ${{ github.workspace }}
          # mkdir build
          # cmake -DCMAKE_PREFIX_PATH:STRING=C:/msys64/mingw64/lib/cmake/ -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CC_COMPILER:FILEPATH=C:/msys64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:/msys64/mingw64/bin/g++.exe -S${{ github.workspace }} -B${{ github.workspace }}\build\ -G "MinGW Makefiles"
          # set /a coreCount=%NUMBER_OF_PROCESSORS% + 2
          # cmake --build ${{ github.workspace }}\build\ --config Debug --target all -j %coreCount% --
          ${{ github.workspace }}/scripts/build.bat
      - name: Run Unit Tests
        run: |
          cd ${{ github.workspace }}\build\tests\
          ./tests.exe
