name: WINDOWS_CI4

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
        run:
          shell: cmd
    steps:
      - name: Install MSYS2
        run: |
            mkdir ${{github.workspace}}/msys2
            cd ${{github.workspace}}/msys2
            curl -LO http://github.com/msys2/msys2-installer/releases/download/2022-12-16/msys2-x86_64-20221216.exe --ssl-no-revoke
            msys2-x86_64-20221216.exe install --root ${{github.workspace}}/msys2 --confirm-command
            set PATH=%PATH%;${{github.workspace}}/msys2/usr/bin
            set PATH=%PATH%;${{github.workspace}}/msys2/mingw64/bin

      - name: Install MSYS2 Packages
        run: |
            cd ${{github.workspace}}/msys2/usr/bin/
            pacman.exe -S mingw-w64-x86_64-qt5
            pacman.exe -S mingw-w64-x86_64-qt5-base
            pacman.exe -S mingw-w64-x86_64-qt5-declarative
            pacman.exe -S mingw-w64-x86_64-cmake
            pacman.exe -S mingw-w64-x86_64-make
            pacman.exe -S mingw-w64-x86_64-gtest
            pacman.exe -S mingw-w64-x86_64-yaml-cpp
            pacman.exe -S mingw-w64-x86_64-ninja

      - name: Build All
        run: |
            mkdir ${{github.workspace}}/build
            cmake -B ${{github.workspace}}/build -G "MinGW Makefiles"
            cmake --build ${{github.workspace}}/build --config Release --target all