name: WINDOWS_CI_3

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
        run:
          shell: msys2 {0}
    steps:    
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
#          location: D:\deneme
          update: true
          install: |
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-declarative
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-yaml-cpp
            mingw-w64-x86_64-ninja
            
        #--> MSYS2_PATH="/usr/local/bin:/usr/bin:/bin"
        #  D:\a\_temp\setup-msys2\msys2.CMD {0} --> cmd

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build All
        run: |
          # TODO - find the correct path to the msys installation
          mkdir runCmake
          cd runCmake
          ls
          dir
          echo "build path is: $(pwd)/build:$PATH"
          echo "make path is :  $MAKE" 
          echo "make path is :  $(mkfile_path)" 
          
          cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_PREFIX_PATH:STRING=/d/a/SpaceLoader/SpaceLoader/runCmake/CMakeFiles/
      

          

#/d/deneme/build:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
#/d/a/_temp/setup-msys2/build:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

#          cd "D://a//_temp//setup-msys2//" 


#          cmake -DCMAKE_PREFIX_PATH:STRING=/msys64/mingw64/lib/cmake/
#           -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
#           -DCMAKE_BUILD_TYPE:STRING=Debug
#           -DCMAKE_CC_COMPILER:FILEPATH=/mingw64/bin/gcc.exe 
#           -DCMAKE_CXX_COMPILER:FILEPATH=/mingw64/bin/g++.exe
#           -S /d/SpaceLoader/SpaceLoader/ 
#           -B /d/SpaceLoader/SpaceLoader/build/ 
#           -G "MinGW Makefiles"
#          set /a coreCount=%NUMBER_OF_PROCESSORS% + 2
#          cmake --build /d/SpaceLoader/SpaceLoader/build/ --config Debug --target all -j %coreCount% --

#      - name: Run Unit Tests
#        run: |
#          cd D:/a/SpaceLoader/SpaceLoader/build/tests/
#          ./tests.exe
